"""initial migration

Revision ID: 27d329ea8a57
Revises: 7476854a9709
Create Date: 2025-08-07 19:24:55.883623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d329ea8a57'
down_revision: Union[str, None] = '7476854a9709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commentmodel', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commentmodel', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
