"""initial migration

Revision ID: dfe97e5329ea
Revises: acfcd294ac64
Create Date: 2025-07-27 20:42:52.082526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe97e5329ea'
down_revision: Union[str, None] = 'acfcd294ac64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('refresh_token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermodel', 'refresh_token')
    # ### end Alembic commands ###
